# Generated by Django 2.1.2 on 2019-01-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='conf',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='division',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fuera',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ultimo10',
        ),
    ]
