# Generated by Django 2.1.2 on 2019-01-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20190121_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='puntosFuera',
            new_name='puntosFavor',
        ),
    ]
