# Generated by Django 2.1.2 on 2019-01-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20190122_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('local', models.CharField(max_length=50)),
                ('visitante', models.CharField(max_length=50)),
                ('ptoL', models.CharField(blank=True, max_length=10, null=True)),
                ('ptoV', models.CharField(blank=True, max_length=10, null=True)),
                ('hora', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
