# Generated by Django 2.1.2 on 2019-01-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_jornada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jornada',
            old_name='ptoL',
            new_name='puntosL',
        ),
        migrations.RenameField(
            model_name='jornada',
            old_name='ptoV',
            new_name='puntosV',
        ),
    ]
