# Generated by Django 2.1.2 on 2019-01-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20190122_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Equipo'),
        ),
    ]
