# Generated by Django 2.1.2 on 2019-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20190122_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='referencia',
            field=models.CharField(max_length=50),
        ),
    ]
