# Generated by Django 2.1.2 on 2019-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20190122_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='logos', verbose_name='Imagen'),
        ),
    ]
