# Generated by Django 2.1.2 on 2019-01-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20190122_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
